### ISSUE TITLE
Analizar colores para el sitio utilizando conceptos de diseño, accesibilidad y estetica

### ISSUE THREAD

**Issue by julianismaellunaarecha** [julianismaellunaarecha/akshu#2]
Analizar colores para el sitio utilizando conceptos de diseño, accesibilidad y estetica

Existen ciertos estandares, aqui una lista:
https://www.argentina.gob.ar/sites/default/files/pautas-de-accesibilidad-para-el-contenido-de-la-web.pdf
https://www.w3.org/standards/webdesign/accessibility
https://www.w3.org/WAI/standards-guidelines/
https://www.w3.org/WAI/standards-guidelines/wcag/
https://www.w3.org/TR/WCAG20/
https://www.w3.org/TR/WCAG21/
https://www.w3schools.com/accessibility/accessibility_intro.php
https://www.w3schools.com/html/html_accessibility.asp

Algunos recursos disponibles:
https://contrastchecker.com/
https://color.adobe.com/
https://webgradients.com/
https://theme-fusion.com/web-aesthetics-short-sweet-guide-memorable-design/
https://www.appliedi.net/blog/7-elements-of-an-aesthetically-pleasing-website/

**Comment by vmponce** [comment]
Buenos días!
Agrego información con análisis y propuesta, en función a lo solicitado. Por supuesto, todo está sujeto a modificación y mejora.

**DISEÑO/ ESTRUCTURA:**
Proponemos un diseño minimalista para que las páginas no se vean tan cargadas en su forma y contenido. Consideramos que por la naturaleza del sitio (venta de productos tecnológicos) donde irán apareciendo los productos que se venden, las  publicidades asociadas, los slide show/ carrousel con más imágenes, la información extra que se agrega vinculada a la accesibilidad, etc. es importante reducir la cantidad y disposición del contenido, sumando espacios en blanco donde sea necesario. 
En este sentido la estructura presentará sutiles variaciones conforme la página concreta del sitio donde nos encontremos y partirá de la base de las maquetas elaboradas por Juli con leves propuestas de modificación, tomando como referencias los sitios web de: https://www.dafiti.com.ar/ y https://www.everlane.com 

Sobre lo dicho se proponen dos variantes minimalistas:
1) No utiliza logotipo/s, isologotipos, etc. y los colores oscilan mayormente entre el blanco, negro y gris de la paleta propuesta, con mínimos toques en amarillo y naranja para resaltar divisiones en el contenido o llamar la atención en publicidades u otras llamadas a la acción.  Las imagenes de los productos pueden estar en colores, tratando de favorecer los pasteles o en blanco y negro o en escala de grises, deberíamos probarlo. 
Esta elección no constituiría un inconveniente en cuando a la escasez de colores porque sigue con lo minimalista y podría, tal como lo implementa Everlane (en su diseño, desde el botón de accesibilidad situado al final de la página principal, asociado al icono de una silueta de persona) darle la posibilidad de personalización a cada usuario en particular, respecto de los colores, tipografías, elección de elementos en movimiento, etc. vinculados a diferentes tipos de discapacidad. 

2) Utiliza un isologo muy pequeño (combinación de imagen con texto o las mismas letras de akshus en amarillo y naranja) y los colores en general de las paginas oscilan entre el blanco, negro y gris de la paleta propuesta, con mayor predominancia de  amarillo y naranja para brindar detalles puntuales, resaltar divisiones en el contenido o llamar la atención en publicidades u otras llamadas a la acción. Si bien habría más libertad en los colores de las imagenes de los productos trataría de mantener los pasteles, blanco o negro o en escala de grises. 

**NOTAS**
Aquí es importante considerar las siguientes combinaciones dentro de la paleta propuesta y que mayormente generan un contraste mínimo (con relación de 4,5:1 conforme al nivel AA de conformidad), situación esencial para la accesibilidad visual:
-fondo gris texto amarillo (relación de 4,5:1, AA)
-fondo amarillo texto gris (relación de 4,63:1, AA)
-fondo amarillo texto negro (relación de 15,7:1, AAA) resaltante, apto para publicidades llamativas del sitio o detalles muy sutiles como poseen Dafiti o Everlane en el header. 
-fondo negro texto amarillo (relación de 15,7:1, AAA) ídem anterior
-fondo negro texto naranja (relación de 9,67:1, AAA) ídem anterior
-fondo naranja texto negro (relación de 9,67:1, AAA) menos resaltante, podría usarse en franjas divisorias de contenido. 
-fondo negro texto blanco (relación de 21:1, AAA) resaltante
-fondo blanco texto negro (relación de 21:1, AAA) menos resaltante, mayormente utilizado en el sitio para la información del contenido en general, donde no se desea generar mayor atención.

*Como detalle extra utilizaremos juegos con tipografías y tamaños, por ejemplo en publicidades u otros, a fin de generar contraste entre las mismas, motivar la lectura del contenido y generar un cierto toque de seriedad y elegancia. Por ej. una fuente en negrita como Futura Medium se puede combinar con una fuente más delgada de tipo de letra similar como Futura para crear títulos o subtítulos. O si usa solo un tipo de letra, Georgia , puede tener un encabezado más fuerte y más grande con el cuerpo del texto en un color más claro para crear contraste.

**TIPOGRAFÍA:**
A fin de favorecer la lectura en pantalla,generar emoción y sensación de claridad en la cognición utilizamos tipografías en la línea Sans Serifs (letras de palo seco, sin serifas o sin remates en su trazo). Las mismas son adecuadas al medio digital (son claras, se entienden) y para grandes pasajes de texto (en los que no ralentizan la lectura a diferencia de otras tipografías). 
Con sus formas geométricas transmiten modernidad, amabilidad, practicidad… cuestiones que deseamos realzar a partir de la venta de productos tecnológicos actuales y que buscan facilitar la vida cotidiana y profesional de nuestro público objetivo.
Dentro de estas tipografías legibles (Helvetica, Azura, Proxima Nova Regular, etc. ) adoptamos aquellas que son más acordes al test de legibilidad Il1 dado que si bien: "No es el determinante definitivo de la legibilidad, sin dudas ayuda". 
Las tipografías en este caso que vamos a combinar son la minimalista Poppins (para los títulos y cabeceras) de facil lectura, elegante y neutra y Open Sans que combina con Poppins y utilizaremos mayormente para el contenido. Ambas serán importadas desde el sitio de Google Fonts, seleccionando algunos estilos de los propuestos para ir creando algunas variaciones. Por otra parte, y ante alguna eventualidad en el reconocimiento se proponen como alternativas las tipografías: 
-Arial, Helvetica, sans-serif.
-Tahoma, Geneva, sans-serif, con las que podrían hacerse algunos juegos de los antes descriptos.

**Tamaño**
Respecto del tamaño adoptamos el mínimo propuesto en la actualidad, esto es, 16 puntos para el contenido (en lugar de 12) teniendo en cuenta que se ha demostrado que los tamaños de fuente más grandes pueden provocar una conexión emocional más fuerte y 22 píxeles para los títulos y cabeceras. 

**Longitud de la línea**
En caso de utilizar textos extensos, adoptamos la regla de "líneas entre 50 y 75 caracteres"; o "como máximo 78 caracteres" dado que se ha demostrado que esta última longitud es más efectiva para ayudar a los lectores a moverse a través de su ruta de escaneo (patrones en E, F, L, L invertida, regla de los saltos de palabras en la lectura, entre otros).
Si la longitud de la línea es demasiado corta, el ritmo de su lector se romperá porque sus ojos deben volver a la izquierda de la página con demasiada frecuencia, se le hará difícil además encontrar dónde comienzan y terminan las líneas de texto. 

**Espacio entre caracteres**
Es recomendable que sea adecuado, para favorecer la legibilidad.

**Espacio entre líneas**
El espacio adecuado entre las líneas permite al lector escanear el texto y acceder a él en los puntos deseados.
Tomamos en este punto como sugerencia que el espacio entre párrafos (que en la web se traduce como margen o relleno colocado en la parte superior o inferior de un párrafo) sea alrededor de la mitad de la altura de la línea. Esto tiende a ayudar a que los pasajes de texto se “mantengan juntos” en lugar de usar un retorno completo entre cada párrafo, creando grandes cantidades de espacio entre párrafos.

**REFERENCIAS:**
https://thenextweb.com/news/science-behind-fonts-make-feel
https://www.staffdigital.pe/blog/colores-diseno-web/ 
https://universomeraki.com/combinaciones-tipograficas-google-fonts/ 
https://fonts.google.com/
https://webdesign.tutsplus.com/articles/typographic-readability-and-legibility--webdesign-12211 
https://piktochart.com/blog/typography-things-you-need-to-know-to-pair-fonts-well/
https://www.shopify.com/blog/11863377-30-beautiful-and-creative-ecommerce-website-designs 
https://imborrable.com/blog/google-fonts/
https://color.adobe.com/es/create/color-contrast-analyzer
