### ISSUE TITLE
Crear primeros css

### ISSUE THREAD

**Issue by julianismaellunaarecha** [julianismaellunaarecha/akshu#8]
Crear primeros css, decidir si utilizamos uno solo en comun o lo dividimos en varios.

Una buena organizacion seria utilizar uno comun para cosas generales de vista, y luego individuales para cada html para las diferentes etiquetas semanticas / clases.

Primera y unica sub-tarea en esta tarea es colocar un fondo o decidir si dejarlo vacio. Se pueden utilizar degrades.

**Comment by vmponce** [comment]
Fecha máxima de terminación: 11/10, 22 hs.
